# Generated by Django 2.0.5 on 2018-05-06 05:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustdoistUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('todoist_token', models.CharField(max_length=128, null=True, unique=True)),
                ('last_problem_shown', models.DateTimeField(null=True)),
                ('inbox_id', models.IntegerField(null=True)),
                ('avatar', models.CharField(max_length=256, null=True)),
                ('color', models.CharField(default='#e44332ff', max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.URLField(max_length=500)),
                ('is_premium', models.BooleanField()),
                ('users', models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=256)),
                ('days', models.IntegerField(default=7)),
                ('end', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('steps_completed', models.IntegerField(default=0)),
                ('is_being_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1)),
                ('description', models.CharField(max_length=10000)),
                ('task', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='StepTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoist_task_id', models.CharField(default='0', max_length=10000)),
                ('related_problem_prob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_trackers', to='main.ProblemProbability')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_trackers', to='main.ProblemStep')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedProblem',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=10000)),
                ('steps_num', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='problemstep',
            name='related_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.SuggestedProblem'),
        ),
        migrations.AddField(
            model_name='problemprobability',
            name='suggested_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='main.SuggestedProblem'),
        ),
        migrations.AddField(
            model_name='problemprobability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
