# Generated by Django 2.0.5 on 2018-05-03 13:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustdoistUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('todoist_token', models.CharField(max_length=128, unique=True)),
                ('last_problem_shown', models.DateTimeField(null=True)),
                ('inbox_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('steps_completed', models.IntegerField(default=0)),
                ('is_being_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedProblem',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=10000)),
                ('steps', models.CharField(max_length=10000)),
                ('steps_num', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='problemprobability',
            name='suggested_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='main.SuggestedProblem'),
        ),
        migrations.AddField(
            model_name='problemprobability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_problems', to='main.JustdoistUser'),
        ),
    ]
