# Generated by Django 2.0.5 on 2018-05-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='price',
        ),
    ]
