# Generated by Django 2.0.5 on 2018-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justdoistuser',
            name='shown_first_task_ac',
            field=models.BooleanField(default=False),
        ),
    ]
