# Generated by Django 2.0.5 on 2018-05-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180505_1837'),
        ('main', '0002_remove_premiumsubscription_price'),
    ]

    operations = [
    ]
