# Generated by Django 2.0.5 on 2018-05-05 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20180505_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.URLField(max_length=500)),
                ('is_premium', models.BooleanField()),
                ('users', models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='todoist_task_id',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
