# Generated by Django 2.0.5 on 2018-05-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180505_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='justdoistuser',
            name='avatar',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
