# Generated by Django 2.0.5 on 2018-05-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_justdoistuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='justdoistuser',
            name='color',
            field=models.CharField(default='#e44332ff', max_length=8),
        ),
    ]
