"""empty message

Revision ID: 2b2579c7f7bf
Revises: 3fb792ee5a4a
Create Date: 2018-02-15 11:59:35.214352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2579c7f7bf'
down_revision = '3fb792ee5a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_probability', sa.Column('steps_completed', sa.Integer(), nullable=True))
    op.add_column('problems', sa.Column('steps_num', sa.Integer(), nullable=True))
    op.add_column('problems', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_problem_shown', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_problem_shown')
    op.drop_column('problems', 'title')
    op.drop_column('problems', 'steps_num')
    op.drop_column('problem_probability', 'steps_completed')
    # ### end Alembic commands ###
