"""users table

Revision ID: 3fb792ee5a4a
Revises: 
Create Date: 2018-02-13 19:53:22.984699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb792ee5a4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=True),
    sa.Column('steps', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todoist_token', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_probability',
    sa.Column('val', sa.Float(), nullable=True),
    sa.Column('problem_num', sa.Integer(), nullable=True),
    sa.Column('user_token', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['users.todoist_token'], ),
    sa.PrimaryKeyConstraint('user_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_probability')
    op.drop_table('users')
    op.drop_table('problems')
    # ### end Alembic commands ###
