"""empty message

Revision ID: 44838de293fd
Revises: 
Create Date: 2018-02-15 13:57:22.820355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44838de293fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=10000), nullable=True),
    sa.Column('steps', sa.String(length=10000), nullable=True),
    sa.Column('steps_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todoist_token', sa.String(length=128), nullable=True),
    sa.Column('last_problem_shown', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_probability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('val', sa.Float(), nullable=True),
    sa.Column('problem_num', sa.Integer(), nullable=True),
    sa.Column('user_token', sa.String(length=128), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('is_being_solved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_token'], ['users.todoist_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_probability')
    op.drop_table('users')
    op.drop_table('problems')
    # ### end Alembic commands ###
