"""empty message

Revision ID: 8e8ce4c5035a
Revises: 2b2579c7f7bf
Create Date: 2018-02-15 12:52:37.082676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8ce4c5035a'
down_revision = '2b2579c7f7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_probability', sa.Column('is_being_solved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_probability', 'is_being_solved')
    # ### end Alembic commands ###
